### Importación de datos

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda1 = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda1.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

In [2]:
tienda1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

In [3]:
tiendas = [tienda1, tienda2, tienda3, tienda4]

for tienda in tiendas:
  print(tienda.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2358 entries, 0 to 2357
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2358 non-null   object
 1   Categoría del Producto  2358 non-null   object
 2   Precio                  2358 non-null   float64
 3   Costo de envío          2358 non-null   float64
 4   Fecha de Compra         2358 non-null   object
 5   Vendedor                2358 non-null   object
 6   Lugar de Compra         2358 non-null   object
 7   Calificación            2358 non-null   int64
 8   Método de pago          2358 non-null   object
 9   Cantidad de cuotas      2358 non-null   int64
 10  lat                     2358 non-null   float64
 11  lon                     2358 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.2+ KB
None

#1. Análisis de facturación

In [4]:
resultados = []

todas_las_tiendas = [tienda1, tienda2, tienda3, tienda4]

for i, df in enumerate(todas_las_tiendas):
    tienda_num = i + 1  # Get the store number (1-indexed)

    facturacion = df['Precio'].sum()

    resultados.append({
        'Tienda': tienda_num,
        'Facturacion_Total': facturacion,
        'Ventas_Registradas': len(df),
        'Precio_Promedio': df['Precio'].mean()
    })

df_resultados = pd.DataFrame(resultados)
df_resultados = df_resultados.sort_values('Facturacion_Total')

In [5]:
pd.options.display.float_format = '{:,.2f}'.format
df_resultados

   Tienda  Facturacion_Total  Ventas_Registradas  Precio_Promedio
3       4   1,038,375,700.00                2358       440,362.89
2       3   1,098,019,600.00                2359       465,459.77
1       2   1,116,343,500.00                2359       473,227.43
0       1   1,150,880,400.00                2359       487,867.91

In [6]:
# Ventas por Forma de pago

formas_pago = []

for i, df in enumerate(todas_las_tiendas):
  tienda_num = i + 1
  df_formas_pago_tienda = df.groupby('Método de pago')['Precio'].sum().reset_index()
  df_formas_pago_tienda['Tienda'] = tienda_num

  formas_pago.append(df_formas_pago_tienda)

df_formas_pago = pd.concat(formas_pago)
df_formas_pago = df_formas_pago.rename(columns={'Precio': 'Total ventas'})

df_formas_pago_por_tienda = df_formas_pago.pivot(index= 'Método de pago', columns= ['Tienda'], values= 'Total ventas')
df_formas_pago_por_tienda.columns = [f'Tienda_{col}' for col in df_formas_pago_por_tienda.columns]
df_formas_pago_por_tienda.reset_index(inplace=True)

# Calcular las ventas totales globales por método de pago
total_ventas_globales = df_formas_pago.groupby('Método de pago')['Total ventas'].sum().reset_index()
total_ventas_globales = total_ventas_globales.rename(columns={'Total ventas': 'Ventas_Totales_Globales'})

# Combinar la tabla pivote con las ventas totales globales
df_formas_pago_final = pd.merge(df_formas_pago_por_tienda, total_ventas_globales, on='Método de pago', how='left')

df_formas_pago_final.sort_values(by='Ventas_Totales_Globales', ascending=False)

,Método de pago,Tienda_1,Tienda_2,Tienda_3,Tienda_4,Ventas_Totales_Globales
2,Tarjeta de crédito,"840,665,800.00","816,659,500.00","804,570,700.00","768,711,100.00","3,230,607,100.00"
1,Nequi,"232,609,700.00","210,748,800.00","229,322,400.00","208,003,300.00","880,684,200.00"
0,Cupón,"64,105,500.00","77,366,600.00","47,411,300.00","46,986,200.00","235,869,600.00"
3,Tarjeta de débito,"13,499,400.00","11,568,600.00","16,715,200.00","14,675,100.00","56,458,300.00"

# 2. Ventas por categoría

In [7]:
ventas_por_categoria = []

for i, df in enumerate(todas_las_tiendas):
    tienda_num = i + 1
    ventas_categoria_tienda = df.groupby('Categoría del Producto')['Precio'].sum().reset_index()
    ventas_categoria_tienda['Tienda'] = tienda_num
    ventas_por_categoria.append(ventas_categoria_tienda)

df_ventas_por_categoria = pd.concat(ventas_por_categoria)

# Agrupar por categoría a través de todas las tiendas para obtener un resumen general
df_ventas_categoria_total = df_ventas_por_categoria.groupby('Categoría del Producto')['Precio'].sum().reset_index()
df_ventas_categoria_total = df_ventas_categoria_total.rename(columns={'Precio': 'Ventas_Totales'})
df_ventas_categoria_total = df_ventas_categoria_total.sort_values(by='Ventas_Totales', ascending=False)

#Agrupar Categorías por tienda
df_ventas_categoria_tienda = df_ventas_por_categoria.groupby(['Tienda', 'Categoría del Producto'])['Precio'].sum().reset_index()
df_ventas_categoria_tienda = df_ventas_categoria_tienda.rename(columns={'Precio': 'Ventas_por_Tienda'})

df_ventas_pivot = df_ventas_categoria_tienda.pivot(index='Categoría del Producto', columns='Tienda', values='Ventas_por_Tienda')
df_ventas_categoria_final = pd.merge(df_ventas_categoria_total, df_ventas_pivot, on='Categoría del Producto', how='left')
# Renombrar las columnas de tienda para mayor claridad, por ejemplo 'Tienda_1', 'Tienda_2', etc.
df_ventas_categoria_final.columns = ['Categoría del Producto', 'Ventas_Totales'] + [f'Tienda_{col}' for col in
                                                                                    df_ventas_categoria_final.columns[2:]]

df_ventas_categoria_final

,Categoría del Producto,Ventas_Totales,Tienda_1,Tienda_2,Tienda_3,Tienda_4
0,Electrónicos,"1,660,576,500.00","429,493,500.00","410,831,100.00","410,775,800.00","409,476,100.00"
1,Electrodomésticos,"1,324,751,100.00","363,685,200.00","348,567,800.00","329,237,900.00","283,260,200.00"
2,Muebles,"757,661,000.00","187,633,700.00","176,426,300.00","201,072,100.00","192,528,900.00"
3,Instrumentos musicales,"348,772,600.00","91,299,000.00","104,990,300.00","77,380,900.00","75,102,400.00"
4,Deportes y diversión,"142,977,700.00","39,290,000.00","34,744,500.00","35,593,100.00","33,350,100.00"
5,Juguetes,"73,604,400.00","17,995,700.00","15,945,400.00","19,401,100.00","20,262,200.00"
6,Artículos para el hogar,"57,579,800.00","12,698,400.00","14,746,900.00","15,060,000.00","15,074,500.00"
7,Libros,"37,696,100.00","8,784,900.00","10,091,200.00","9,498,700.00","9,321,300.00"

# 3. Calificación promedio de la tienda

In [8]:
calificaciones_promedio = []

for i, df in enumerate(todas_las_tiendas):
    tienda_num = i + 1
    calificacion_promedio = df['Calificación'].mean()
    calificaciones_promedio.append({'Tienda': tienda_num, 'Calificacion_Promedio': calificacion_promedio})

df_calificaciones_promedio = pd.DataFrame(calificaciones_promedio)
df_calificaciones_promedio = df_calificaciones_promedio.sort_values(by='Calificacion_Promedio', ascending=False)

In [9]:
df_calificaciones_promedio

   Tienda  Calificacion_Promedio
2       3                   4.05
1       2                   4.04
3       4                   4.00
0       1                   3.98

# 4. Productos más y menos vendidos

In [10]:
top_bottom_productos_por_tienda = []

for i, df in enumerate(todas_las_tiendas):
    tienda_num = i + 1
    ventas_por_producto = df.groupby('Producto')['Precio'].sum().reset_index()
    ventas_por_producto = ventas_por_producto.rename(columns={'Precio': 'Ventas_Totales'})

    # Productos más vendidos por tienda
    top_productos = ventas_por_producto.nlargest(5, 'Ventas_Totales')
    top_productos['Tipo'] = 'Top 5'
    top_productos['Tienda'] = tienda_num

    # Productos menos vendidos por tienda
    bottom_productos = ventas_por_producto.nsmallest(5, 'Ventas_Totales')
    bottom_productos['Tipo'] = 'Bottom 5'
    bottom_productos['Tienda'] = tienda_num

    top_bottom_productos_por_tienda.append(top_productos)
    top_bottom_productos_por_tienda.append(bottom_productos)

df_top_bottom_productos_por_tienda = pd.concat(top_bottom_productos_por_tienda)

print('Top 5 y Bottom 5 Productos por Tienda:')
print(df_top_bottom_productos_por_tienda)

Top 5 y Bottom 5 Productos por Tienda:
                   Producto  Ventas_Totales      Tipo  Tienda
48            TV LED UHD 4K  142,150,200.00     Top 5       1
39             Refrigerador  112,143,300.00     Top 5       1
25                Iphone 15   97,902,200.00     Top 5       1
45                 Smart TV   67,452,100.00     Top 5       1
28         Lavadora de ropa   65,783,600.00     Top 5       1
17       Cuerda para saltar      652,800.00  Bottom 5       1
19           Dinosaurio Rex      688,900.00  Bottom 5       1
16          Cubo mágico 8x8      696,900.00  Bottom 5       1
42             Set de vasos    1,359,100.00  Bottom 5       1
0         Ajedrez de madera    1,430,600.00  Bottom 5       1
25                Iphone 15  113,225,800.00     Top 5       2
48            TV LED UHD 4K  103,375,000.00     Top 5       2
39             Refrigerador   97,632,500.00     Top 5       2
28         Lavadora de ropa   66,762,300.00     Top 5       2
45                 Smart TV   61,142,000.00     Top 5       2
16          Cubo mágico 8x8      643,600.00  Bottom 5       2
19           Dinosaurio Rex      770,300.00  Bottom 5       2
17       Cuerda para saltar      856,900.00  Bottom 5       2
0         Ajedrez de madera    1,287,700.00  Bottom 5       2
42             Set de vasos    1,542,600.00  Bottom 5       2
39             Refrigerador   99,889,700.00     Top 5       3
48            TV LED UHD 4K   96,669,100.00     Top 5       3
25                Iphone 15   93,225,700.00     Top 5       3
45                 Smart TV   78,837,300.00     Top 5       3
29             Lavavajillas   64,364,800.00     Top 5       3
16          Cubo mágico 8x8      640,400.00  Bottom 5       3
19           Dinosaurio Rex      795,600.00  Bottom 5       3
17       Cuerda para saltar      853,800.00  Bottom 5       3
42             Set de vasos    1,210,700.00  Bottom 5       3
9   Bloques de construcción    1,237,200.00  Bottom 5       3
25                Iphone 15   96,697,500.00     Top 5       4
48            TV LED UHD 4K   90,295,300.00     Top 5       4
45                 Smart TV   82,790,400.00     Top 5       4
39             Refrigerador   75,271,900.00     Top 5       4
49              Tablet ABXY   56,723,100.00     Top 5       4
17       Cuerda para saltar      704,800.00  Bottom 5       4
16          Cubo mágico 8x8      748,400.00  Bottom 5       4
19           Dinosaurio Rex      858,100.00  Bottom 5       4
0         Ajedrez de madera    1,075,500.00  Bottom 5       4
42             Set de vasos    1,471,800.00  Bottom 5       4

In [11]:
# Análisis global de productos más y menos vendidos
ventas_por_producto_global = pd.concat(todas_las_tiendas).groupby('Producto')['Precio'].sum().reset_index()
ventas_por_producto_global = ventas_por_producto_global.rename(columns={'Precio': 'Ventas_Totales'})

# Top 5 productos global
top_productos_global = ventas_por_producto_global.nlargest(5, 'Ventas_Totales')
top_productos_global['Tipo'] = 'Top 5 Global'

# Bottom 5 productos global
bottom_productos_global = ventas_por_producto_global.nsmallest(5, 'Ventas_Totales')
bottom_productos_global['Tipo'] = 'Bottom 5 Global'

df_productos_global = pd.concat([top_productos_global, bottom_productos_global])

print('\nTop 5 y Bottom 5 Productos Globales:')
print(df_productos_global)

Top 5 y Bottom 5 Productos Globales:
              Producto  Ventas_Totales             Tipo
48       TV LED UHD 4K  432,489,600.00     Top 5 Global
25           Iphone 15  401,051,200.00     Top 5 Global
39        Refrigerador  384,937,400.00     Top 5 Global
45            Smart TV  290,221,800.00     Top 5 Global
28    Lavadora de ropa  242,468,600.00     Top 5 Global
16     Cubo mágico 8x8    2,729,300.00  Bottom 5 Global
17  Cuerda para saltar    3,068,300.00  Bottom 5 Global
19      Dinosaurio Rex    3,112,900.00  Bottom 5 Global
0    Ajedrez de madera    5,149,100.00  Bottom 5 Global
42        Set de vasos    5,584,200.00  Bottom 5 Global

# 5. Envío promedio por tienda

In [12]:
envios_promedio = []

for i, df in enumerate(todas_las_tiendas):
    tienda_num = i + 1
    envio_promedio = df['Costo de envío'].mean()
    envios_promedio.append({'Tienda': tienda_num, 'Envio_Promedio': envio_promedio})

df_envios_promedio = pd.DataFrame(envios_promedio)
df_envios_promedio = df_envios_promedio.sort_values(by='Envio_Promedio', ascending=False)

In [13]:
df_envios_promedio

   Tienda  Envio_Promedio
0       1       26,018.61
1       2       25,216.24
2       3       24,805.68
3       4       23,459.46